name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f docker/docker-compose.yml up --build --force-recreate
      
      - name: Check if container is running
        run: /bin/bash -c "[[ $(docker ps -qf "name=docker_python-pddl") != "" ]] && echo "Ok" || exit 1"

