name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
  
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f docker/docker-compose.yml up
      
      - name: Check if container is running
        run: docker ps -qf "name=docker_python-pddl"

      - name: Run the Test Suite
        run: docker exec -it $(docker ps -qf "name=docker_python-pddl") /bin/bash -c "python3 -c 'from jupyddl.__init__ import *''
      
      - name: Exit Python3
        run: exit()
      
      - name: Exit Docker
        run: exit
